() => {
	try {
	} catch (Exception e) {
	} finally {
	}
}